<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit565ae4454a3bba9b74acce07c2adc4fb
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'e40631d46120a9c38ea139981f8dab26' => __DIR__ . '/..' . '/ircmaxell/password-compat/lib/password.php',
        '2c102faa651ef8ea5874edb585946bce' => __DIR__ . '/..' . '/swiftmailer/swiftmailer/lib/swift_required.php',
        '3919eeb97e98d4648304477f8ef734ba' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/Crypt/Random.php',
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
        '58571171fd5812e6e447dce228f52f4d' => __DIR__ . '/..' . '/laravel/framework/src/Illuminate/Support/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'Zizaco\\Entrust\\' => 15,
            'Zizaco\\Confide\\' => 15,
        ),
        'T' => 
        array (
            'TijsVerkoyen\\CssToInlineStyles\\' => 31,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\Security\\Core\\' => 32,
            'Symfony\\Component\\Routing\\' => 26,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\HttpKernel\\' => 29,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\Filesystem\\' => 29,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'Symfony\\Component\\DomCrawler\\' => 29,
            'Symfony\\Component\\Debug\\' => 24,
            'Symfony\\Component\\CssSelector\\' => 30,
            'Symfony\\Component\\Console\\' => 26,
            'Symfony\\Component\\BrowserKit\\' => 29,
        ),
        'R' => 
        array (
            'Riskihajar\\Terbilang\\' => 21,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Patchwork\\' => 10,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'L' => 
        array (
            'Laravel\\' => 8,
        ),
        'K' => 
        array (
            'Knp\\Snappy\\' => 11,
        ),
        'H' => 
        array (
            'HtmlObject\\' => 11,
        ),
        'F' => 
        array (
            'Former\\' => 7,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Inflector\\' => 26,
            'Doctrine\\Common\\Cache\\' => 22,
            'Doctrine\\Common\\Annotations\\' => 28,
            'Doctrine\\Common\\' => 16,
        ),
        'C' => 
        array (
            'Carbon\\' => 7,
        ),
        'B' => 
        array (
            'Barryvdh\\DomPDF\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Zizaco\\Entrust\\' => 
        array (
            0 => __DIR__ . '/..' . '/zizaco/entrust/src/Entrust',
        ),
        'Zizaco\\Confide\\' => 
        array (
            0 => __DIR__ . '/..' . '/zizaco/confide/src/Confide',
        ),
        'TijsVerkoyen\\CssToInlineStyles\\' => 
        array (
            0 => __DIR__ . '/..' . '/tijsverkoyen/css-to-inline-styles/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\Security\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-core',
        ),
        'Symfony\\Component\\Routing\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/routing',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\HttpKernel\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-kernel',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Symfony\\Component\\DomCrawler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dom-crawler',
        ),
        'Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/debug',
        ),
        'Symfony\\Component\\CssSelector\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/css-selector',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Symfony\\Component\\BrowserKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/browser-kit',
        ),
        'Riskihajar\\Terbilang\\' => 
        array (
            0 => __DIR__ . '/..' . '/riskihajar/terbilang/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Patchwork\\' => 
        array (
            0 => __DIR__ . '/..' . '/patchwork/utf8/src/Patchwork',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Laravel\\' => 
        array (
            0 => __DIR__ . '/..' . '/anahkiasen/former/src/Laravel',
        ),
        'Knp\\Snappy\\' => 
        array (
            0 => __DIR__ . '/..' . '/knplabs/knp-snappy/src/Knp/Snappy',
        ),
        'HtmlObject\\' => 
        array (
            0 => __DIR__ . '/..' . '/anahkiasen/html-object/src',
        ),
        'Former\\' => 
        array (
            0 => __DIR__ . '/..' . '/anahkiasen/former/src/Former',
            1 => __DIR__ . '/..' . '/anahkiasen/former/tests',
        ),
        'Doctrine\\Common\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/lib/Doctrine/Common/Inflector',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Doctrine\\Common\\Annotations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/annotations/lib/Doctrine/Common/Annotations',
        ),
        'Doctrine\\Common\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/common/lib/Doctrine/Common',
        ),
        'Carbon\\' => 
        array (
            0 => __DIR__ . '/..' . '/nesbot/carbon/src/Carbon',
        ),
        'Barryvdh\\DomPDF\\' => 
        array (
            0 => __DIR__ . '/..' . '/barryvdh/laravel-dompdf/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'X' => 
        array (
            'Xethron\\MigrationsGenerator' => 
            array (
                0 => __DIR__ . '/..' . '/xethron/migrations-generator/src',
            ),
        ),
        'W' => 
        array (
            'Whoops' => 
            array (
                0 => __DIR__ . '/..' . '/filp/whoops/src',
            ),
            'Way\\Generators' => 
            array (
                0 => __DIR__ . '/..' . '/way/generators/src',
            ),
        ),
        'S' => 
        array (
            'System' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
            'Stack' => 
            array (
                0 => __DIR__ . '/..' . '/stack/builder/src',
            ),
        ),
        'P' => 
        array (
            'Predis' => 
            array (
                0 => __DIR__ . '/..' . '/predis/predis/lib',
            ),
            'PHPParser' => 
            array (
                0 => __DIR__ . '/..' . '/nikic/php-parser/lib',
            ),
            'PHPExcel' => 
            array (
                0 => __DIR__ . '/..' . '/phpoffice/phpexcel/Classes',
            ),
        ),
        'N' => 
        array (
            'Net' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
        ),
        'M' => 
        array (
            'Milon\\Barcode' => 
            array (
                0 => __DIR__ . '/..' . '/milon/barcode/src',
            ),
            'Math' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
            'Maatwebsite\\Excel\\' => 
            array (
                0 => __DIR__ . '/..' . '/maatwebsite/excel/src',
            ),
        ),
        'L' => 
        array (
            'LaravelBook\\Ardent' => 
            array (
                0 => __DIR__ . '/..' . '/laravelbook/ardent/src',
            ),
        ),
        'J' => 
        array (
            'Jeremeamia\\SuperClosure' => 
            array (
                0 => __DIR__ . '/..' . '/jeremeamia/SuperClosure/src',
            ),
        ),
        'I' => 
        array (
            'Illuminate' => 
            array (
                0 => __DIR__ . '/..' . '/laravel/framework/src',
            ),
        ),
        'F' => 
        array (
            'File' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
        ),
        'C' => 
        array (
            'Crypt' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
            'Cornford\\Backup' => 
            array (
                0 => __DIR__ . '/..' . '/cornford/backup/src',
            ),
            'ClassPreloader' => 
            array (
                0 => __DIR__ . '/..' . '/classpreloader/classpreloader/src',
            ),
        ),
        'B' => 
        array (
            'Boris' => 
            array (
                0 => __DIR__ . '/..' . '/d11wtq/boris/lib',
            ),
            'Barryvdh\\Snappy' => 
            array (
                0 => __DIR__ . '/..' . '/barryvdh/laravel-snappy/src',
            ),
        ),
    );

    public static $classMap = array (
        'Absolute_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/absolute_positioner.cls.php',
        'Abstract_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/abstract_renderer.cls.php',
        'Account' => __DIR__ . '/../..' . '/app/models/Account.php',
        'AccountController' => __DIR__ . '/../..' . '/app/controllers/AccountController.php',
        'AccountTransaction' => __DIR__ . '/../..' . '/app/models/AccountTransaction.php',
        'Accounts' => __DIR__ . '/../..' . '/app/models/Accounts.php',
        'AccountsController' => __DIR__ . '/../..' . '/app/controllers/AccountsController.php',
        'AddCategoryToClientTable' => __DIR__ . '/../..' . '/app/database/migrations/2016_09_15_223520_add_category_to_client_table.php',
        'AddCommentColumnInErporder' => __DIR__ . '/../..' . '/app/database/migrations/2016_09_08_161324_add_comment_column_in_erporder.php',
        'AddForeignKeysToXAssignedRolesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_assigned_roles_table.php',
        'AddForeignKeysToXChargeLoanproductTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_charge_loanproduct_table.php',
        'AddForeignKeysToXChargeSavingproductTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_charge_savingproduct_table.php',
        'AddForeignKeysToXJournalsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_journals_table.php',
        'AddForeignKeysToXKinsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_kins_table.php',
        'AddForeignKeysToXLoanaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_loanaccounts_table.php',
        'AddForeignKeysToXLoanguarantorsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_loanguarantors_table.php',
        'AddForeignKeysToXLoanpostingsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_loanpostings_table.php',
        'AddForeignKeysToXLoanrepaymentsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_loanrepayments_table.php',
        'AddForeignKeysToXLoantransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_loantransactions_table.php',
        'AddForeignKeysToXMembersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_members_table.php',
        'AddForeignKeysToXOrdersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_orders_table.php',
        'AddForeignKeysToXPermissionRoleTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_permission_role_table.php',
        'AddForeignKeysToXProductsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_products_table.php',
        'AddForeignKeysToXSavingaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_savingaccounts_table.php',
        'AddForeignKeysToXSavingpostingsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_savingpostings_table.php',
        'AddForeignKeysToXSavingtransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_savingtransactions_table.php',
        'AddForeignKeysToXShareaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_shareaccounts_table.php',
        'AddForeignKeysToXSharetransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_sharetransactions_table.php',
        'AddForeignKeysToXUserRoleTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_user_role_table.php',
        'AddForeignKeysToXUsersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192006_add_foreign_keys_to_x_users_table.php',
        'AddXRefNoToExpensesTable' => __DIR__ . '/../..' . '/app/database/migrations/2016_10_06_145141_add_x_ref_no_to_expenses_table.php',
        'Adobe_Font_Metrics' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Adobe_Font_Metrics.php',
        'Allowance' => __DIR__ . '/../..' . '/app/models/Allowance.php',
        'AllowancesController' => __DIR__ . '/../..' . '/app/controllers/AllowancesController.php',
        'Assigndriver' => __DIR__ . '/../..' . '/app/models/Assigndriver.php',
        'AssigndriversController' => __DIR__ . '/../..' . '/app/controllers/AssigndriversController.php',
        'Attribute_Translator' => __DIR__ . '/..' . '/dompdf/dompdf/include/attribute_translator.cls.php',
        'Audit' => __DIR__ . '/../..' . '/app/models/Audit.php',
        'AuditsController' => __DIR__ . '/../..' . '/app/controllers/AuditsController.php',
        'Autoprocess' => __DIR__ . '/../..' . '/app/models/Autoprocess.php',
        'AutoprocessesController' => __DIR__ . '/../..' . '/app/controllers/AutoprocessesController.php',
        'AutoprocessesTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/AutoprocessesTableSeeder.php',
        'BBranch' => __DIR__ . '/../..' . '/app/models/BBranch.php',
        'Bank' => __DIR__ . '/../..' . '/app/models/Bank.php',
        'BankAccount' => __DIR__ . '/../..' . '/app/models/BankAccount.php',
        'BankAccountController' => __DIR__ . '/../..' . '/app/controllers/BankAccountController.php',
        'BankBranchController' => __DIR__ . '/../..' . '/app/controllers/BankBranchController.php',
        'BankStatement' => __DIR__ . '/../..' . '/app/models/BankStatement.php',
        'Banking' => __DIR__ . '/../..' . '/app/models/Banking.php',
        'BanksController' => __DIR__ . '/../..' . '/app/controllers/BanksController.php',
        'BaseController' => __DIR__ . '/../..' . '/app/controllers/BaseController.php',
        'Block_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/block_frame_decorator.cls.php',
        'Block_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/block_frame_reflower.cls.php',
        'Block_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/block_positioner.cls.php',
        'Block_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/block_renderer.cls.php',
        'Branch' => __DIR__ . '/../..' . '/app/models/Branch.php',
        'BranchesController' => __DIR__ . '/../..' . '/app/controllers/BranchesController.php',
        'CPDF_Adapter' => __DIR__ . '/..' . '/dompdf/dompdf/include/cpdf_adapter.cls.php',
        'CSS_Color' => __DIR__ . '/..' . '/dompdf/dompdf/include/css_color.cls.php',
        'Cached_PDF_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/cached_pdf_decorator.cls.php',
        'Canvas' => __DIR__ . '/..' . '/dompdf/dompdf/include/canvas.cls.php',
        'Canvas_Factory' => __DIR__ . '/..' . '/dompdf/dompdf/include/canvas_factory.cls.php',
        'CategoriesController' => __DIR__ . '/../..' . '/app/controllers/CategoriesController.php',
        'Category' => __DIR__ . '/../..' . '/app/models/Category.php',
        'Cellmap' => __DIR__ . '/..' . '/dompdf/dompdf/include/cellmap.cls.php',
        'Charge' => __DIR__ . '/../..' . '/app/models/Charge.php',
        'ChargesController' => __DIR__ . '/../..' . '/app/controllers/ChargesController.php',
        'Client' => __DIR__ . '/../..' . '/app/models/Client.php',
        'ClientsController' => __DIR__ . '/../..' . '/app/controllers/ClientsController.php',
        'ClientsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/ClientsTableSeeder.php',
        'ConfideSetupUsersTable' => __DIR__ . '/..' . '/zizaco/confide/src/migrations/2013_01_13_172956_confide_setup_users_table.php',
        'CreateAllowancesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_125654_create_allowances_table.php',
        'CreateAssigndriversTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_07_13_104738_create_assigndrivers_table.php',
        'CreateAutoprocessesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_20_083755_create_autoprocesses_table.php',
        'CreateBankBranchesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_131641_create_bank_branches_table.php',
        'CreateBankReconciliationTables' => __DIR__ . '/../..' . '/app/database/migrations/2016_10_13_144052_create_bank_reconciliation_tables.php',
        'CreateBankTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_104621_create_bank_table.php',
        'CreateClientsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_093206_create_clients_table.php',
        'CreateCompanyPropertyTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_135019_create_company_property_table.php',
        'CreateDeductionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_105006_create_deductions_table.php',
        'CreateDepartmentsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_101925_create_departments_table.php',
        'CreateDocumentsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_134419_create_documents_table.php',
        'CreateDriversTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_07_13_104738_create_drivers_table.php',
        'CreateEarningsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_122642_create_earnings_table.php',
        'CreateEducationTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_103046_create_education_table.php',
        'CreateEmployeeAllowancesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_130039_create_employee_allowances_table.php',
        'CreateEmployeeDeductionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_132013_create_employee_deductions_table.php',
        'CreateEmployeeReliefTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_105530_create_employee_relief_table.php',
        'CreateEmployeeTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_072830_create_employee_table.php',
        'CreateEmployeeTypeTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_104021_create_employee_type_table.php',
        'CreateErporderitemsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_101046_create_erporderitems_table.php',
        'CreateErpordersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_095700_create_erporders_table.php',
        'CreateExpensesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_094633_create_expenses_table.php',
        'CreateHolidaysController' => __DIR__ . '/../..' . '/app/controllers/CreateHolidaysController.php',
        'CreateHolidaysTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_11_074541_create_holidays_table.php',
        'CreateItemTracker' => __DIR__ . '/../..' . '/app/database/migrations/2016_09_19_110601_create_item_tracker.php',
        'CreateItemsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_092634_create_items_table.php',
        'CreateJobGroupTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_102341_create_job_group_table.php',
        'CreateLeaveapplicationsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_11_075243_create_leaveapplications_table.php',
        'CreateLeavetypesController' => __DIR__ . '/../..' . '/app/controllers/CreateLeavetypesController.php',
        'CreateLeavetypesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_11_073943_create_leavetypes_table.php',
        'CreateLocationsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_094052_create_locations_table.php',
        'CreateMailsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_06_29_104738_create_mails_table.php',
        'CreateNextOfKinTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_134623_create_next_of_kin_table.php',
        'CreateNhifTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_02_060202_create_nhif_table.php',
        'CreateNssfTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_02_060131_create_nssf_table.php',
        'CreatePaymentmethodsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_093509_create_paymentmethods_table.php',
        'CreatePaymentsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_104147_create_payments_table.php',
        'CreatePricesTable' => __DIR__ . '/../..' . '/app/database/migrations/2016_08_04_104739_create_prices_table.php',
        'CreateReliefTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_105430_create_relief_table.php',
        'CreateStocksTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_12_17_104738_create_stocks_table.php',
        'CreateTableAccountTransactions' => __DIR__ . '/../..' . '/app/database/migrations/2016_10_24_230950_create_table_account_transactions.php',
        'CreateTransactAllowancesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_132807_create_transact_allowances_table.php',
        'CreateTransactDeductionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_132807_create_transact_deductions_table.php',
        'CreateTransactEarningsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_133021_create_transact_earnings_table.php',
        'CreateTransactTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_30_133337_create_transact_table.php',
        'CreateVehiclesTable' => __DIR__ . '/../..' . '/app/database/migrations/2016_07_13_104738_create_vehicles_table.php',
        'CreateXAccountTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_account_table.php',
        'CreateXAccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_accounts_table.php',
        'CreateXAssignedRolesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_assigned_roles_table.php',
        'CreateXAuditsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_audits_table.php',
        'CreateXBankingTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_banking_table.php',
        'CreateXBranchesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_branches_table.php',
        'CreateXCategoriesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_categories_table.php',
        'CreateXChargeLoanproductTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_charge_loanproduct_table.php',
        'CreateXChargeSavingproductTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_charge_savingproduct_table.php',
        'CreateXChargesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_charges_table.php',
        'CreateXCurrenciesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_currencies_table.php',
        'CreateXGroupsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_groups_table.php',
        'CreateXJournalsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_journals_table.php',
        'CreateXKinsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_kins_table.php',
        'CreateXLoanaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loanaccounts_table.php',
        'CreateXLoanguarantorsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loanguarantors_table.php',
        'CreateXLoanpostingsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loanpostings_table.php',
        'CreateXLoanproductsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loanproducts_table.php',
        'CreateXLoanrepaymentsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loanrepayments_table.php',
        'CreateXLoantransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_loantransactions_table.php',
        'CreateXMembersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_members_table.php',
        'CreateXOrdersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_orders_table.php',
        'CreateXOrganizationsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_organizations_table.php',
        'CreateXPasswordRemindersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_password_reminders_table.php',
        'CreateXPermissionRoleTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_permission_role_table.php',
        'CreateXPermissionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_permissions_table.php',
        'CreateXProductsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_products_table.php',
        'CreateXRolesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_roles_table.php',
        'CreateXSavingaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_savingaccounts_table.php',
        'CreateXSavingpostingsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_savingpostings_table.php',
        'CreateXSavingproductsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_savingproducts_table.php',
        'CreateXSavingtransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_savingtransactions_table.php',
        'CreateXShareaccountsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_shareaccounts_table.php',
        'CreateXSharesTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_shares_table.php',
        'CreateXSharetransactionsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_sharetransactions_table.php',
        'CreateXTaxOrdersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_tax_orders_table.php',
        'CreateXTaxTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_tax_table.php',
        'CreateXUserRoleTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_user_role_table.php',
        'CreateXUsersTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_users_table.php',
        'CreateXVendorsTable' => __DIR__ . '/../..' . '/app/database/migrations/2015_11_13_192002_create_x_vendors_table.php',
        'CreateXsalestargetTable' => __DIR__ . '/../..' . '/app/database/migrations/2016_07_08_192002_create_x_salestarget_table.php',
        'CurrenciesController' => __DIR__ . '/../..' . '/app/controllers/CurrenciesController.php',
        'Currency' => __DIR__ . '/../..' . '/app/models/Currency.php',
        'DOMPDF' => __DIR__ . '/..' . '/dompdf/dompdf/include/dompdf.cls.php',
        'DOMPDF_Exception' => __DIR__ . '/..' . '/dompdf/dompdf/include/dompdf_exception.cls.php',
        'DOMPDF_Image_Exception' => __DIR__ . '/..' . '/dompdf/dompdf/include/dompdf_image_exception.cls.php',
        'DashboardController' => __DIR__ . '/../..' . '/app/controllers/DashboardController.php',
        'DatabaseSeeder' => __DIR__ . '/../..' . '/app/database/seeds/TenantsTableSeeder.php',
        'Deduction' => __DIR__ . '/../..' . '/app/models/Deduction.php',
        'DeductionsController' => __DIR__ . '/../..' . '/app/controllers/DeductionsController.php',
        'Department' => __DIR__ . '/../..' . '/app/models/Department.php',
        'DepartmentsController' => __DIR__ . '/../..' . '/app/controllers/DepartmentsController.php',
        'Driver' => __DIR__ . '/../..' . '/app/models/Driver.php',
        'DriversController' => __DIR__ . '/../..' . '/app/controllers/DriversController.php',
        'EAllowances' => __DIR__ . '/../..' . '/app/models/EAllowances.php',
        'EDeduction' => __DIR__ . '/../..' . '/app/models/EDeduction.php',
        'ERelief' => __DIR__ . '/../..' . '/app/models/ERelief.php',
        'EType' => __DIR__ . '/../..' . '/app/models/EType.php',
        'Earnings' => __DIR__ . '/../..' . '/app/models/Earnings.php',
        'EarningsController' => __DIR__ . '/../..' . '/app/controllers/EarningsController.php',
        'Employee' => __DIR__ . '/../..' . '/app/models/Employee.php',
        'EmployeeAllowancesController' => __DIR__ . '/../..' . '/app/controllers/EmployeeAllowancesController.php',
        'EmployeeDeductionsController' => __DIR__ . '/../..' . '/app/controllers/EmployeeDeductionsController.php',
        'EmployeeReliefController' => __DIR__ . '/../..' . '/app/controllers/EmployeeReliefController.php',
        'EmployeeTypeController' => __DIR__ . '/../..' . '/app/controllers/EmployeeTypeController.php',
        'EmployeesController' => __DIR__ . '/../..' . '/app/controllers/EmployeesController.php',
        'Encoding_Map' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Encoding_Map.php',
        'ErpReportsController' => __DIR__ . '/../..' . '/app/controllers/ErpReportsController.php',
        'Erporder' => __DIR__ . '/../..' . '/app/models/Erporder.php',
        'Erporderitem' => __DIR__ . '/../..' . '/app/models/Erporderitem.php',
        'ErporderitemsController' => __DIR__ . '/../..' . '/app/controllers/ErporderitemsController.php',
        'ErporderitemsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/ErporderitemsTableSeeder.php',
        'ErpordersController' => __DIR__ . '/../..' . '/app/controllers/ErpordersController.php',
        'ErpordersTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/ErpordersTableSeeder.php',
        'Erppurchase' => __DIR__ . '/../..' . '/app/models/Erppurchase.php',
        'Erppurchaseitem' => __DIR__ . '/../..' . '/app/models/Erppurchaseitem.php',
        'ErppurchaseitemsController' => __DIR__ . '/../..' . '/app/controllers/ErppurchaseitemsController.php',
        'ErppurchasesController' => __DIR__ . '/../..' . '/app/controllers/ErppurchasesController.php',
        'Erpquotation' => __DIR__ . '/../..' . '/app/models/Erpquotation.php',
        'Erpquotationitem' => __DIR__ . '/../..' . '/app/models/Erpquotationitem.php',
        'ErpquotationitemsController' => __DIR__ . '/../..' . '/app/controllers/ErpquotationitemsController.php',
        'ErpquotationsController' => __DIR__ . '/../..' . '/app/controllers/ErpquotationsController.php',
        'Expense' => __DIR__ . '/../..' . '/app/models/Expense.php',
        'ExpensesController' => __DIR__ . '/../..' . '/app/controllers/ExpensesController.php',
        'ExpensesTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/ExpensesTableSeeder.php',
        'Fixed_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/fixed_positioner.cls.php',
        'Font' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font.php',
        'Font_Binary_Stream' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Binary_Stream.php',
        'Font_EOT' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_EOT.php',
        'Font_EOT_Header' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_EOT_Header.php',
        'Font_Glyph_Outline' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Glyph_Outline.php',
        'Font_Glyph_Outline_Component' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Glyph_Outline_Component.php',
        'Font_Glyph_Outline_Composite' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Glyph_Outline_Composite.php',
        'Font_Glyph_Outline_Simple' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Glyph_Outline_Simple.php',
        'Font_Header' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Header.php',
        'Font_Metrics' => __DIR__ . '/..' . '/dompdf/dompdf/include/font_metrics.cls.php',
        'Font_OpenType' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_OpenType.php',
        'Font_OpenType_Table_Directory_Entry' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_OpenType_Table_Directory_Entry.php',
        'Font_Table' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table.php',
        'Font_Table_Directory_Entry' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_Directory_Entry.php',
        'Font_Table_cmap' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_cmap.php',
        'Font_Table_glyf' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_glyf.php',
        'Font_Table_head' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_head.php',
        'Font_Table_hhea' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_hhea.php',
        'Font_Table_hmtx' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_hmtx.php',
        'Font_Table_kern' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_kern.php',
        'Font_Table_loca' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_loca.php',
        'Font_Table_maxp' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_maxp.php',
        'Font_Table_name' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_name.php',
        'Font_Table_name_Record' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_name_Record.php',
        'Font_Table_os2' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_os2.php',
        'Font_Table_post' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_Table_post.php',
        'Font_TrueType' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_TrueType.php',
        'Font_TrueType_Collection' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_TrueType_Collection.php',
        'Font_TrueType_Header' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_TrueType_Header.php',
        'Font_TrueType_Table_Directory_Entry' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_TrueType_Table_Directory_Entry.php',
        'Font_WOFF' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_WOFF.php',
        'Font_WOFF_Header' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_WOFF_Header.php',
        'Font_WOFF_Table_Directory_Entry' => __DIR__ . '/..' . '/phenx/php-font-lib/classes/Font_WOFF_Table_Directory_Entry.php',
        'Frame' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame.cls.php',
        'FrameList' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame.cls.php',
        'FrameListIterator' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame.cls.php',
        'FrameTreeIterator' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame.cls.php',
        'FrameTreeList' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame.cls.php',
        'Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame_decorator.cls.php',
        'Frame_Factory' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame_factory.cls.php',
        'Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame_reflower.cls.php',
        'Frame_Tree' => __DIR__ . '/..' . '/dompdf/dompdf/include/frame_tree.cls.php',
        'GD_Adapter' => __DIR__ . '/..' . '/dompdf/dompdf/include/gd_adapter.cls.php',
        'Group' => __DIR__ . '/../..' . '/app/models/Group.php',
        'GroupsController' => __DIR__ . '/../..' . '/app/controllers/GroupsController.php',
        'Holiday' => __DIR__ . '/../..' . '/app/models/Holiday.php',
        'HolidaysController' => __DIR__ . '/../..' . '/app/controllers/HolidaysController.php',
        'HolidaysTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/HolidaysTableSeeder.php',
        'IlluminateQueueClosure' => __DIR__ . '/..' . '/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php',
        'Image_Cache' => __DIR__ . '/..' . '/dompdf/dompdf/include/image_cache.cls.php',
        'Image_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/image_frame_decorator.cls.php',
        'Image_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/image_frame_reflower.cls.php',
        'Image_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/image_renderer.cls.php',
        'Inline_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/inline_frame_decorator.cls.php',
        'Inline_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/inline_frame_reflower.cls.php',
        'Inline_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/inline_positioner.cls.php',
        'Inline_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/inline_renderer.cls.php',
        'Item' => __DIR__ . '/../..' . '/app/models/Item.php',
        'ItemTracker' => __DIR__ . '/../..' . '/app/models/ItemTracker.php',
        'ItemsController' => __DIR__ . '/../..' . '/app/controllers/ItemsController.php',
        'ItemsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/ItemsTableSeeder.php',
        'JGroup' => __DIR__ . '/../..' . '/app/models/JGroup.php',
        'Javascript_Embedder' => __DIR__ . '/..' . '/dompdf/dompdf/include/javascript_embedder.cls.php',
        'JobGroupController' => __DIR__ . '/../..' . '/app/controllers/JobGroupController.php',
        'Journal' => __DIR__ . '/../..' . '/app/models/Journal.php',
        'JournalsController' => __DIR__ . '/../..' . '/app/controllers/JournalsController.php',
        'Kin' => __DIR__ . '/../..' . '/app/models/Kin.php',
        'KinsController' => __DIR__ . '/../..' . '/app/controllers/KinsController.php',
        'Leaveapplication' => __DIR__ . '/../..' . '/app/models/Leaveapplication.php',
        'LeaveapplicationsController' => __DIR__ . '/../..' . '/app/controllers/LeaveapplicationsController.php',
        'LeaveapplicationsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/LeaveapplicationsTableSeeder.php',
        'Leavetype' => __DIR__ . '/../..' . '/app/models/Leavetype.php',
        'LeavetypesController' => __DIR__ . '/../..' . '/app/controllers/LeavetypesController.php',
        'LeavetypesTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/LeavetypesTableSeeder.php',
        'Line_Box' => __DIR__ . '/..' . '/dompdf/dompdf/include/line_box.cls.php',
        'List_Bullet_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/list_bullet_frame_decorator.cls.php',
        'List_Bullet_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/list_bullet_frame_reflower.cls.php',
        'List_Bullet_Image_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/list_bullet_image_frame_decorator.cls.php',
        'List_Bullet_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/list_bullet_positioner.cls.php',
        'List_Bullet_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/list_bullet_renderer.cls.php',
        'Loanaccount' => __DIR__ . '/../..' . '/app/models/Loanaccount.php',
        'LoanaccountsController' => __DIR__ . '/../..' . '/app/controllers/LoanaccountsController.php',
        'Loancharge' => __DIR__ . '/../..' . '/app/models/Loancharge.php',
        'LoanchargesController' => __DIR__ . '/../..' . '/app/controllers/LoanchargesController.php',
        'Loanguarantor' => __DIR__ . '/../..' . '/app/models/Loanguarantor.php',
        'LoanguarantorsController' => __DIR__ . '/../..' . '/app/controllers/LoanguarantorsController.php',
        'Loanposting' => __DIR__ . '/../..' . '/app/models/Loanposting.php',
        'LoanpostingsController' => __DIR__ . '/../..' . '/app/controllers/LoanpostingsController.php',
        'Loanproduct' => __DIR__ . '/../..' . '/app/models/Loanproduct.php',
        'LoanproductsController' => __DIR__ . '/../..' . '/app/controllers/LoanproductsController.php',
        'Loanrepayment' => __DIR__ . '/../..' . '/app/models/Loanrepayment.php',
        'LoanrepaymentsController' => __DIR__ . '/../..' . '/app/controllers/LoanrepaymentsController.php',
        'Loantransaction' => __DIR__ . '/../..' . '/app/models/Loantransaction.php',
        'LoantransactionsController' => __DIR__ . '/../..' . '/app/controllers/LoantransactionsController.php',
        'Location' => __DIR__ . '/../..' . '/app/models/Location.php',
        'LocationsController' => __DIR__ . '/../..' . '/app/controllers/LocationsController.php',
        'LocationsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/LocationsTableSeeder.php',
        'Maatwebsite\\Excel\\Classes\\Cache' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Classes/Cache.php',
        'Maatwebsite\\Excel\\Classes\\FormatIdentifier' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Classes/FormatIdentifier.php',
        'Maatwebsite\\Excel\\Classes\\LaravelExcelWorksheet' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Classes/LaravelExcelWorksheet.php',
        'Maatwebsite\\Excel\\Classes\\PHPExcel' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Classes/PHPExcel.php',
        'Maatwebsite\\Excel\\Collections\\CellCollection' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Collections/CellCollection.php',
        'Maatwebsite\\Excel\\Collections\\ExcelCollection' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Collections/ExcelCollection.php',
        'Maatwebsite\\Excel\\Collections\\RowCollection' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Collections/RowCollection.php',
        'Maatwebsite\\Excel\\Collections\\SheetCollection' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Collections/SheetCollection.php',
        'Maatwebsite\\Excel\\Excel' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Excel.php',
        'Maatwebsite\\Excel\\ExcelServiceProvider' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/ExcelServiceProvider.php',
        'Maatwebsite\\Excel\\Exceptions\\LaravelExcelException' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Exceptions/LaravelExcelException.php',
        'Maatwebsite\\Excel\\Facades\\Excel' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Facades/Excel.php',
        'Maatwebsite\\Excel\\Files\\ExcelFile' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Files/ExcelFile.php',
        'Maatwebsite\\Excel\\Files\\ExportHandler' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Files/ExportHandler.php',
        'Maatwebsite\\Excel\\Files\\File' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Files/File.php',
        'Maatwebsite\\Excel\\Files\\ImportHandler' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Files/ImportHandler.php',
        'Maatwebsite\\Excel\\Files\\NewExcelFile' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Files/NewExcelFile.php',
        'Maatwebsite\\Excel\\Filters\\ChunkReadFilter' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Filters/ChunkReadFilter.php',
        'Maatwebsite\\Excel\\Parsers\\CssParser' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Parsers/CssParser.php',
        'Maatwebsite\\Excel\\Parsers\\ExcelParser' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Parsers/ExcelParser.php',
        'Maatwebsite\\Excel\\Parsers\\ViewParser' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Parsers/ViewParser.php',
        'Maatwebsite\\Excel\\Readers\\Batch' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Readers/Batch.php',
        'Maatwebsite\\Excel\\Readers\\ConfigReader' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Readers/ConfigReader.php',
        'Maatwebsite\\Excel\\Readers\\Html' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Readers/HtmlReader.php',
        'Maatwebsite\\Excel\\Readers\\LaravelExcelReader' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Readers/LaravelExcelReader.php',
        'Maatwebsite\\Excel\\Writers\\CellWriter' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Writers/CellWriter.php',
        'Maatwebsite\\Excel\\Writers\\LaravelExcelWriter' => __DIR__ . '/..' . '/maatwebsite/excel/src/Maatwebsite/Excel/Writers/LaravelExcelWriter.php',
        'MailsController' => __DIR__ . '/../..' . '/app/controllers/MailsController.php',
        'Mailsender' => __DIR__ . '/../..' . '/app/models/Mail.php',
        'Member' => __DIR__ . '/../..' . '/app/models/Member.php',
        'MembersController' => __DIR__ . '/../..' . '/app/controllers/MembersController.php',
        'NhifController' => __DIR__ . '/../..' . '/app/controllers/NhifController.php',
        'NhifRates' => __DIR__ . '/../..' . '/app/models/NhifRates.php',
        'Normalizer' => __DIR__ . '/..' . '/patchwork/utf8/src/Normalizer.php',
        'NssfController' => __DIR__ . '/../..' . '/app/controllers/NssfController.php',
        'NssfRates' => __DIR__ . '/../..' . '/app/models/NssfRates.php',
        'Null_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/null_frame_decorator.cls.php',
        'Null_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/null_frame_reflower.cls.php',
        'Null_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/null_positioner.cls.php',
        'Order' => __DIR__ . '/../..' . '/app/models/Order.php',
        'OrdersController' => __DIR__ . '/../..' . '/app/controllers/OrdersController.php',
        'Organization' => __DIR__ . '/../..' . '/app/models/Organization.php',
        'OrganizationsController' => __DIR__ . '/../..' . '/app/controllers/OrganizationsController.php',
        'PDFLib_Adapter' => __DIR__ . '/..' . '/dompdf/dompdf/include/pdflib_adapter.cls.php',
        'PHP_Evaluator' => __DIR__ . '/..' . '/dompdf/dompdf/include/php_evaluator.cls.php',
        'Page_Cache' => __DIR__ . '/..' . '/dompdf/dompdf/include/page_cache.cls.php',
        'Page_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/page_frame_decorator.cls.php',
        'Page_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/page_frame_reflower.cls.php',
        'Payment' => __DIR__ . '/../..' . '/app/models/Payment.php',
        'Paymentmethod' => __DIR__ . '/../..' . '/app/models/Paymentmethod.php',
        'PaymentmethodsController' => __DIR__ . '/../..' . '/app/controllers/PaymentmethodsController.php',
        'PaymentmethodsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/PaymentmethodsTableSeeder.php',
        'PaymentsController' => __DIR__ . '/../..' . '/app/controllers/PaymentsController.php',
        'PaymentsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/PaymentsTableSeeder.php',
        'Payroll' => __DIR__ . '/../..' . '/app/models/Payroll.php',
        'PayrollController' => __DIR__ . '/../..' . '/app/controllers/PayrollController.php',
        'Permission' => __DIR__ . '/../..' . '/app/models/Permission.php',
        'Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/positioner.cls.php',
        'Price' => __DIR__ . '/../..' . '/app/models/Price.php',
        'PricesController' => __DIR__ . '/../..' . '/app/controllers/PricesController.php',
        'Product' => __DIR__ . '/../..' . '/app/models/Product.php',
        'ProductsController' => __DIR__ . '/../..' . '/app/controllers/ProductsController.php',
        'Relief' => __DIR__ . '/../..' . '/app/models/Relief.php',
        'ReliefsController' => __DIR__ . '/../..' . '/app/controllers/ReliefsController.php',
        'Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/renderer.cls.php',
        'ReportsController' => __DIR__ . '/../..' . '/app/controllers/ReportsController.php',
        'Role' => __DIR__ . '/../..' . '/app/models/Role.php',
        'RolesController' => __DIR__ . '/../..' . '/app/controllers/RolesController.php',
        'SalesTarget' => __DIR__ . '/../..' . '/app/models/SalesTarget.php',
        'SalestargetController' => __DIR__ . '/../..' . '/app/controllers/SalestargetController.php',
        'Savingaccount' => __DIR__ . '/../..' . '/app/models/Savingaccount.php',
        'SavingaccountsController' => __DIR__ . '/../..' . '/app/controllers/SavingaccountsController.php',
        'Savingcharge' => __DIR__ . '/../..' . '/app/models/Savingcharge.php',
        'SavingchargesController' => __DIR__ . '/../..' . '/app/controllers/SavingchargesController.php',
        'Savingposting' => __DIR__ . '/../..' . '/app/models/Savingposting.php',
        'SavingpostingsController' => __DIR__ . '/../..' . '/app/controllers/SavingpostingsController.php',
        'Savingproduct' => __DIR__ . '/../..' . '/app/models/Savingproduct.php',
        'SavingproductsController' => __DIR__ . '/../..' . '/app/controllers/SavingproductsController.php',
        'Savingtransaction' => __DIR__ . '/../..' . '/app/models/Savingtransaction.php',
        'SavingtransactionsController' => __DIR__ . '/../..' . '/app/controllers/SavingtransactionsController.php',
        'SessionHandlerInterface' => __DIR__ . '/..' . '/symfony/http-foundation/Resources/stubs/SessionHandlerInterface.php',
        'Share' => __DIR__ . '/../..' . '/app/models/Share.php',
        'Shareaccount' => __DIR__ . '/../..' . '/app/models/Shareaccount.php',
        'ShareaccountsController' => __DIR__ . '/../..' . '/app/controllers/ShareaccountsController.php',
        'SharesController' => __DIR__ . '/../..' . '/app/controllers/SharesController.php',
        'Sharetransaction' => __DIR__ . '/../..' . '/app/models/Sharetransaction.php',
        'SharetransactionsController' => __DIR__ . '/../..' . '/app/controllers/SharetransactionsController.php',
        'StmtTransaction' => __DIR__ . '/../..' . '/app/models/StmtTransaction.php',
        'Stock' => __DIR__ . '/../..' . '/app/models/Stock.php',
        'StocksController' => __DIR__ . '/../..' . '/app/controllers/StocksController.php',
        'StocksTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/StocksTableSeeder.php',
        'Style' => __DIR__ . '/..' . '/dompdf/dompdf/include/style.cls.php',
        'Stylesheet' => __DIR__ . '/..' . '/dompdf/dompdf/include/stylesheet.cls.php',
        'TCPDF_Adapter' => __DIR__ . '/..' . '/dompdf/dompdf/include/tcpdf_adapter.cls.php',
        'Table_Cell_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_cell_frame_decorator.cls.php',
        'Table_Cell_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_cell_frame_reflower.cls.php',
        'Table_Cell_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_cell_positioner.cls.php',
        'Table_Cell_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_cell_renderer.cls.php',
        'Table_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_frame_decorator.cls.php',
        'Table_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_frame_reflower.cls.php',
        'Table_Row_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_frame_decorator.cls.php',
        'Table_Row_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_frame_reflower.cls.php',
        'Table_Row_Group_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_group_frame_decorator.cls.php',
        'Table_Row_Group_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_group_frame_reflower.cls.php',
        'Table_Row_Group_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_group_renderer.cls.php',
        'Table_Row_Positioner' => __DIR__ . '/..' . '/dompdf/dompdf/include/table_row_positioner.cls.php',
        'Tax' => __DIR__ . '/../..' . '/app/models/Tax.php',
        'TaxController' => __DIR__ . '/../..' . '/app/controllers/TaxController.php',
        'TaxOrder' => __DIR__ . '/../..' . '/app/models/TaxOrder.php',
        'TenantsTableSeeder' => __DIR__ . '/../..' . '/app/database/seeds/TenantsTableSeeder.php',
        'TestCase' => __DIR__ . '/../..' . '/app/tests/TestCase.php',
        'Text_Frame_Decorator' => __DIR__ . '/..' . '/dompdf/dompdf/include/text_frame_decorator.cls.php',
        'Text_Frame_Reflower' => __DIR__ . '/..' . '/dompdf/dompdf/include/text_frame_reflower.cls.php',
        'Text_Renderer' => __DIR__ . '/..' . '/dompdf/dompdf/include/text_renderer.cls.php',
        'Traits\\Encryptable' => __DIR__ . '/../..' . '/app/traits/Encryptable.php',
        'User' => __DIR__ . '/../..' . '/app/models/User.php',
        'UserRepository' => __DIR__ . '/../..' . '/app/models/UserRepository.php',
        'UsersController' => __DIR__ . '/../..' . '/app/controllers/UsersController.php',
        'Vehicle' => __DIR__ . '/../..' . '/app/models/Vehicle.php',
        'VehiclesController' => __DIR__ . '/../..' . '/app/controllers/VehiclesController.php',
        'Vendor' => __DIR__ . '/../..' . '/app/models/Vendor.php',
        'VendorsController' => __DIR__ . '/../..' . '/app/controllers/VendorsController.php',
        'Whoops\\Module' => __DIR__ . '/..' . '/filp/whoops/src/deprecated/Zend/Module.php',
        'Whoops\\Provider\\Zend\\ExceptionStrategy' => __DIR__ . '/..' . '/filp/whoops/src/deprecated/Zend/ExceptionStrategy.php',
        'Whoops\\Provider\\Zend\\RouteNotFoundStrategy' => __DIR__ . '/..' . '/filp/whoops/src/deprecated/Zend/RouteNotFoundStrategy.php',
        'Zizaco\\Confide\\ControllerCommand' => __DIR__ . '/..' . '/zizaco/confide/src/commands/ControllerCommand.php',
        'Zizaco\\Confide\\MigrationCommand' => __DIR__ . '/..' . '/zizaco/confide/src/commands/MigrationCommand.php',
        'Zizaco\\Confide\\RoutesCommand' => __DIR__ . '/..' . '/zizaco/confide/src/commands/RoutesCommand.php',
        'Zizaco\\Entrust\\MigrationCommand' => __DIR__ . '/..' . '/zizaco/entrust/src/commands/MigrationCommand.php',
        'payslipEmailController' => __DIR__ . '/../..' . '/app/controllers/payslipEmailController.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit565ae4454a3bba9b74acce07c2adc4fb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit565ae4454a3bba9b74acce07c2adc4fb::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit565ae4454a3bba9b74acce07c2adc4fb::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit565ae4454a3bba9b74acce07c2adc4fb::$classMap;

        }, null, ClassLoader::class);
    }
}
